import { Inter } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/CommonLayout";
import { QueryProvider } from "@/providers/queryProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gurusharan Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CommonLayout><QueryProvider>{children}</QueryProvider></CommonLayout>
          </body>
    </html>
  );
}
